{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pantau-http-core/2.0.1/pantau-http-core-2.0.1.module",
    "group": "com.pantauhttp",
    "module": "pantau-http-core",
    "version": "2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http-core-iosSimulatorArm64Main-2.0.1.klib",
          "url": "pantau-http-core-iossimulatorarm64-2.0.1.klib",
          "size": 209029,
          "sha512": "4902e9ad6b1a72a8d0962892026de60a8bc16d93dbd2a16ef6ea11f2541c7afb5a40ebee966d164525f5223fc593483189c75fef80645e5b7bec1b39dc7154bd",
          "sha256": "2b7ef61e3742ddca3401041b754b3bc0b2c6d30aa8dda130765c4417664290c9",
          "sha1": "09b16203769eec2518b2c8020c942b0d064b2337",
          "md5": "241e5a0e2383d6fae38882519409d096"
        },
        {
          "name": "pantau-http-core-iosSimulatorArm64Cinterop-PantauShimMain-2.0.1.klib",
          "url": "pantau-http-core-iossimulatorarm64-2.0.1-cinterop-PantauShim.klib",
          "size": 12058,
          "sha512": "c45dd7106f4ed74cefaba43b25e54e794542cbc2903625200d89d2f86fd01a6d4f2e085243882f7f082188f6ab0124f6dcbadd1f7a7f7495b02cf0be75df7190",
          "sha256": "59e1e4ba1ee7c5534f4c53ddbc140ffbbdd7bffc4157ddd6e075c015eec16d0c",
          "sha1": "42ca3cf8e2155520fd1726faef50f3b4c3051065",
          "md5": "7ea4e2999495533f04c5e08d04d24324"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "pantau-http-core-iossimulatorarm64-2.0.1-sources.jar",
          "url": "pantau-http-core-iossimulatorarm64-2.0.1-sources.jar",
          "size": 35143,
          "sha512": "13ec4a975a9e40d2e4c6656afc73d95ff7b687ae7ac28f35ad2be72179fc614becb78394c2d32265de0747750cd2ee1d944fec71cfd3521da63733d48ea735f1",
          "sha256": "dc42df11130751fa23324cd7093bccd23e10d5a6823bb151a86ac9829b67e97c",
          "sha1": "4f6459664c8c9fb5aa176d94b25227c05605d98e",
          "md5": "52a9ff8221ccacf25d3d9f63c66e9c92"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-darwin",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http-core-iossimulatorarm64-2.0.1-metadata.jar",
          "url": "pantau-http-core-iossimulatorarm64-2.0.1-metadata.jar",
          "size": 24592,
          "sha512": "7c6135c75b03c9c1a93b27b9c3c3c2dff133c6e837782fe97f5ffa158922c53df0fa06db4cc470dcff1fdcb422a6e4f67fa3ba7b807f2dc25355078de1b319e9",
          "sha256": "01fe54b5787ab754a74335f564975d4a76d99df62a9cf344e26576ae8ff1dd52",
          "sha1": "4cb9868f5146a85787e857a9c4b786a33e9d33a5",
          "md5": "95cdf75f029fda0f992bcac8be2e620d"
        }
      ]
    }
  ]
}
