{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pantau-http-core/2.0.2/pantau-http-core-2.0.2.module",
    "group": "com.pantauhttp",
    "module": "pantau-http-core",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http-core.aar",
          "url": "pantau-http-core-android-2.0.2.aar",
          "size": 248597,
          "sha512": "5e659c58a013bd9f270ea7dd5afbae40b9a6f04d3a9d8bf1d6445f1916e4e2ccb6f4bdd434b9f8de24de1865fac2bae88ca135192837b36d7185aff1c9e680c9",
          "sha256": "0ce1b34550892664098012406acd8522db7cb74cbef925e39590b2a518c9286e",
          "sha1": "2927dae6f64cdde38993450bd0d8ca6c6351fc22",
          "md5": "b5977c21572f50f87f7a27848d66249e"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.2.3"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http-core.aar",
          "url": "pantau-http-core-android-2.0.2.aar",
          "size": 248597,
          "sha512": "5e659c58a013bd9f270ea7dd5afbae40b9a6f04d3a9d8bf1d6445f1916e4e2ccb6f4bdd434b9f8de24de1865fac2bae88ca135192837b36d7185aff1c9e680c9",
          "sha256": "0ce1b34550892664098012406acd8522db7cb74cbef925e39590b2a518c9286e",
          "sha1": "2927dae6f64cdde38993450bd0d8ca6c6351fc22",
          "md5": "b5977c21572f50f87f7a27848d66249e"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pantau-http-core-android-2.0.2-sources.jar",
          "url": "pantau-http-core-android-2.0.2-sources.jar",
          "size": 36368,
          "sha512": "bfc04cb6c7cfc5a98e098cb401c13199d252c1401d5e24200b471ef86030dfc7126eab22980a5e9455bb3458f8502a2a1b0eea77e52c4928f1796ba3eaee1309",
          "sha256": "5ae3ccd60c37d85dd4e855f82a7f2a2f48138828bbe44f2dda21ecabd75d9dbb",
          "sha1": "5a9d67bea00c651e3b66570c5b5e1441f8d17068",
          "md5": "a3efe756976bb0118e1b7b6acc0d4fc3"
        }
      ]
    }
  ]
}
