{
  "formatVersion": "1.1",
  "component": {
    "url": "../../pantau-http/2.0.2/pantau-http-2.0.2.module",
    "group": "com.pantauhttp",
    "module": "pantau-http",
    "version": "2.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.pantauhttp",
          "module": "pantau-http-core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http.aar",
          "url": "pantau-http-android-2.0.2.aar",
          "size": 114108,
          "sha512": "4b84c8335bdef0012473805e2581086eabc1104ee3ad0a554f3b5314e2537358a3c09f035e5d60235af896c9715141e707a04ee43b13fdfa8e1f42f5b4f6561f",
          "sha256": "fb66fa381b235c814956c948b74ccc9847c4e7f1e81e1ecf0064ece0ea780036",
          "sha1": "b1632507e7f78583884ce68d00a7b5cbb39727df",
          "md5": "e87d655e3b7d660cdfd98a67eb33c683"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.pantauhttp",
          "module": "pantau-http-core",
          "version": {
            "requires": "2.0.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.11.1"
          }
        },
        {
          "group": "org.jetbrains.compose.material",
          "module": "material-icons-core",
          "version": {
            "requires": "1.7.3"
          }
        }
      ],
      "files": [
        {
          "name": "pantau-http.aar",
          "url": "pantau-http-android-2.0.2.aar",
          "size": 114108,
          "sha512": "4b84c8335bdef0012473805e2581086eabc1104ee3ad0a554f3b5314e2537358a3c09f035e5d60235af896c9715141e707a04ee43b13fdfa8e1f42f5b4f6561f",
          "sha256": "fb66fa381b235c814956c948b74ccc9847c4e7f1e81e1ecf0064ece0ea780036",
          "sha1": "b1632507e7f78583884ce68d00a7b5cbb39727df",
          "md5": "e87d655e3b7d660cdfd98a67eb33c683"
        }
      ]
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pantau-http-android-2.0.2-sources.jar",
          "url": "pantau-http-android-2.0.2-sources.jar",
          "size": 13396,
          "sha512": "a395df44fbf80cd2fd50d27c760916bfd5ffbdd3e7330684146207f8745aace58c52cc738c6cf1199300cbd23e52684dbbb391da2d37b385bbaae2c0687902be",
          "sha256": "0199d7bc62affd42e7fc8e7735e6c4e6b6b29c7e9e16b4ee478206d32595d95b",
          "sha1": "267fb611ee70a451f6a1217c7d0ca65c843ea115",
          "md5": "a70475b503644d459c5cbe09793c9490"
        }
      ]
    }
  ]
}
